### PR TITLE
Pass autoQueryFallback option onto QueryInterface

### PR DESCRIPTION
**Pull request by PaulWagener**

### CODE REVIEW

**Comment by ktsashes** [comment]
Was there a reason you needed this on the `QueryInterface` object? `autoQueryFallback` is actually handled mostly by calling code to the `QueryInterface` object (mostly because each function will have different requirements for how it "auto" falls back). Did you need to access it for some other piece of code?

**Comment by PaulWagener** [comment]
We defined autoQueryFallback to be false via the options on the Sequelize object. But it was still true in places like https://github.com/BlinkUX/sequelize-mock/blob/master/src/model.js#L329 resulting in failing tests. We found that this fixed it. But maybe there is a better way.

**Comment by ktsashes** [comment]
Hmm, that's weird. [Line 56 of that Model file](https://github.com/BlinkUX/sequelize-mock/blob/master/src/model.js#L56) should import it from the calling `Sequelize` object and inherit it there.

Can you file a bug on this? I'm going to dig into it a bit and see if I can't find out why that's happening. Hopefully what I find is just this is the fix and I can just merge this in. But I want to check the implications of having that value inherited in the `QueryInterface` object.

**Comment by PaulWagener** [comment]
Hmm, it must've been something on my end because I just tried to recreate the bug and it all worked as expected.

**Pull request closed without merging**
