### PR TITLE
Add FindAndCountAll method and add tests

### PR DESCRIPTION
**Pull request by TerryMooreII**
Here is the FindAndCountAll method and tests

### CODE REVIEW

**Comment by ktsashes** [comment]
Thank you so much for your work! This is a very clean solution and the tests and documentation for it are great.

**Comment by TerryMooreII** [comment]
Any chance you can release the next version of the npm package?  I need this function asap.  Thanks!

**Comment by ktsashes** [comment]
I just pushed v0.10.0 out, and it includes this change

**Comment by TerryMooreII** [comment]
Thanks!!

**Pull request merged**
